// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type Meow struct {
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamp
}
