// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Meow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID                   pgtype.UUID
	Username             string
	DisplayName          string
	Email                string
	EmailVerified        pgtype.Bool
	PasswordHash         string
	ResetPasswordToken   pgtype.Text
	ResetPasswordExpires pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	LastLoginAt          pgtype.Timestamp
	AccountLocked        pgtype.Bool
	FailedLoginAttempts  pgtype.Int4
}
