// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.authors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const indexAuthors = `-- name: IndexAuthors :many
SELECT id, name, created_at
FROM authors
ORDER BY created_at DESC
`

func (q *Queries) IndexAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, indexAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showAuthor = `-- name: ShowAuthor :one
SELECT id, name, created_at
FROM authors
WHERE id = $1
LIMIT 1
`

func (q *Queries) ShowAuthor(ctx context.Context, id pgtype.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, showAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
