// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v4.24.4
// source: meow/v1/meow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meow) Reset() {
	*x = Meow{}
	mi := &file_meow_v1_meow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meow) ProtoMessage() {}

func (x *Meow) ProtoReflect() protoreflect.Message {
	mi := &file_meow_v1_meow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meow.ProtoReflect.Descriptor instead.
func (*Meow) Descriptor() ([]byte, []int) {
	return file_meow_v1_meow_proto_rawDescGZIP(), []int{0}
}

func (x *Meow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Meow) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Meow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateMeowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeowRequest) Reset() {
	*x = CreateMeowRequest{}
	mi := &file_meow_v1_meow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeowRequest) ProtoMessage() {}

func (x *CreateMeowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meow_v1_meow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeowRequest.ProtoReflect.Descriptor instead.
func (*CreateMeowRequest) Descriptor() ([]byte, []int) {
	return file_meow_v1_meow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMeowRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMeowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meow          *Meow                  `protobuf:"bytes,1,opt,name=meow,proto3" json:"meow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeowResponse) Reset() {
	*x = CreateMeowResponse{}
	mi := &file_meow_v1_meow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeowResponse) ProtoMessage() {}

func (x *CreateMeowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meow_v1_meow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeowResponse.ProtoReflect.Descriptor instead.
func (*CreateMeowResponse) Descriptor() ([]byte, []int) {
	return file_meow_v1_meow_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMeowResponse) GetMeow() *Meow {
	if x != nil {
		return x.Meow
	}
	return nil
}

type GetMeowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeowRequest) Reset() {
	*x = GetMeowRequest{}
	mi := &file_meow_v1_meow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeowRequest) ProtoMessage() {}

func (x *GetMeowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meow_v1_meow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeowRequest.ProtoReflect.Descriptor instead.
func (*GetMeowRequest) Descriptor() ([]byte, []int) {
	return file_meow_v1_meow_proto_rawDescGZIP(), []int{3}
}

func (x *GetMeowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMeowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meow          *Meow                  `protobuf:"bytes,1,opt,name=meow,proto3" json:"meow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeowResponse) Reset() {
	*x = GetMeowResponse{}
	mi := &file_meow_v1_meow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeowResponse) ProtoMessage() {}

func (x *GetMeowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meow_v1_meow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeowResponse.ProtoReflect.Descriptor instead.
func (*GetMeowResponse) Descriptor() ([]byte, []int) {
	return file_meow_v1_meow_proto_rawDescGZIP(), []int{4}
}

func (x *GetMeowResponse) GetMeow() *Meow {
	if x != nil {
		return x.Meow
	}
	return nil
}

type IndexMeowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexMeowRequest) Reset() {
	*x = IndexMeowRequest{}
	mi := &file_meow_v1_meow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMeowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMeowRequest) ProtoMessage() {}

func (x *IndexMeowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meow_v1_meow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMeowRequest.ProtoReflect.Descriptor instead.
func (*IndexMeowRequest) Descriptor() ([]byte, []int) {
	return file_meow_v1_meow_proto_rawDescGZIP(), []int{5}
}

type IndexMeowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meows         []*Meow                `protobuf:"bytes,1,rep,name=meows,proto3" json:"meows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexMeowResponse) Reset() {
	*x = IndexMeowResponse{}
	mi := &file_meow_v1_meow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMeowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMeowResponse) ProtoMessage() {}

func (x *IndexMeowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meow_v1_meow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMeowResponse.ProtoReflect.Descriptor instead.
func (*IndexMeowResponse) Descriptor() ([]byte, []int) {
	return file_meow_v1_meow_proto_rawDescGZIP(), []int{6}
}

func (x *IndexMeowResponse) GetMeows() []*Meow {
	if x != nil {
		return x.Meows
	}
	return nil
}

var File_meow_v1_meow_proto protoreflect.FileDescriptor

var file_meow_v1_meow_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x22, 0x4f, 0x0a,
	0x04, 0x4d, 0x65, 0x6f, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2d,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x37, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x6d, 0x65, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6f, 0x77,
	0x52, 0x04, 0x6d, 0x65, 0x6f, 0x77, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6f,
	0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x6d,
	0x65, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x6f, 0x77,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x04, 0x6d, 0x65, 0x6f, 0x77, 0x22, 0x12,
	0x0a, 0x10, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x38, 0x0a, 0x11, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x65, 0x6f, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x6d, 0x65, 0x6f, 0x77, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x05, 0x6d, 0x65, 0x6f, 0x77, 0x73, 0x32, 0xdc, 0x01, 0x0a,
	0x0b, 0x4d, 0x65, 0x6f, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6f, 0x77, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x6f,
	0x77, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6f, 0x77, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6f, 0x77,
	0x12, 0x17, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x6f, 0x77,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x65,
	0x6f, 0x77, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x4d, 0x65, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x6d, 0x65, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x65, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x79, 0x78, 0x50, 0x69,
	0x6e, 0x6b, 0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_meow_v1_meow_proto_rawDescOnce sync.Once
	file_meow_v1_meow_proto_rawDescData = file_meow_v1_meow_proto_rawDesc
)

func file_meow_v1_meow_proto_rawDescGZIP() []byte {
	file_meow_v1_meow_proto_rawDescOnce.Do(func() {
		file_meow_v1_meow_proto_rawDescData = protoimpl.X.CompressGZIP(file_meow_v1_meow_proto_rawDescData)
	})
	return file_meow_v1_meow_proto_rawDescData
}

var file_meow_v1_meow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_meow_v1_meow_proto_goTypes = []any{
	(*Meow)(nil),               // 0: meow.v1.Meow
	(*CreateMeowRequest)(nil),  // 1: meow.v1.CreateMeowRequest
	(*CreateMeowResponse)(nil), // 2: meow.v1.CreateMeowResponse
	(*GetMeowRequest)(nil),     // 3: meow.v1.GetMeowRequest
	(*GetMeowResponse)(nil),    // 4: meow.v1.GetMeowResponse
	(*IndexMeowRequest)(nil),   // 5: meow.v1.IndexMeowRequest
	(*IndexMeowResponse)(nil),  // 6: meow.v1.IndexMeowResponse
}
var file_meow_v1_meow_proto_depIdxs = []int32{
	0, // 0: meow.v1.CreateMeowResponse.meow:type_name -> meow.v1.Meow
	0, // 1: meow.v1.GetMeowResponse.meow:type_name -> meow.v1.Meow
	0, // 2: meow.v1.IndexMeowResponse.meows:type_name -> meow.v1.Meow
	1, // 3: meow.v1.MeowService.CreateMeow:input_type -> meow.v1.CreateMeowRequest
	3, // 4: meow.v1.MeowService.GetMeow:input_type -> meow.v1.GetMeowRequest
	5, // 5: meow.v1.MeowService.IndexMeow:input_type -> meow.v1.IndexMeowRequest
	2, // 6: meow.v1.MeowService.CreateMeow:output_type -> meow.v1.CreateMeowResponse
	4, // 7: meow.v1.MeowService.GetMeow:output_type -> meow.v1.GetMeowResponse
	6, // 8: meow.v1.MeowService.IndexMeow:output_type -> meow.v1.IndexMeowResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_meow_v1_meow_proto_init() }
func file_meow_v1_meow_proto_init() {
	if File_meow_v1_meow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meow_v1_meow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meow_v1_meow_proto_goTypes,
		DependencyIndexes: file_meow_v1_meow_proto_depIdxs,
		MessageInfos:      file_meow_v1_meow_proto_msgTypes,
	}.Build()
	File_meow_v1_meow_proto = out.File
	file_meow_v1_meow_proto_rawDesc = nil
	file_meow_v1_meow_proto_goTypes = nil
	file_meow_v1_meow_proto_depIdxs = nil
}
