// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: author/v1/author.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_author_v1_author_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_author_v1_author_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorResponse) Reset() {
	*x = CreateAuthorResponse{}
	mi := &file_author_v1_author_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorResponse) ProtoMessage() {}

func (x *CreateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_author_v1_author_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_author_v1_author_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type IndexAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexAuthorRequest) Reset() {
	*x = IndexAuthorRequest{}
	mi := &file_author_v1_author_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexAuthorRequest) ProtoMessage() {}

func (x *IndexAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexAuthorRequest.ProtoReflect.Descriptor instead.
func (*IndexAuthorRequest) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{5}
}

type IndexAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexAuthorResponse) Reset() {
	*x = IndexAuthorResponse{}
	mi := &file_author_v1_author_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexAuthorResponse) ProtoMessage() {}

func (x *IndexAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexAuthorResponse.ProtoReflect.Descriptor instead.
func (*IndexAuthorResponse) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{6}
}

func (x *IndexAuthorResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

var File_author_v1_author_proto protoreflect.FileDescriptor

const file_author_v1_author_proto_rawDesc = "" +
	"\n" +
	"\x16author/v1/author.proto\x12\tauthor.v1\"K\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\")\n" +
	"\x13CreateAuthorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x14CreateAuthorResponse\x12)\n" +
	"\x06author\x18\x01 \x01(\v2\x11.author.v1.AuthorR\x06author\"\"\n" +
	"\x10GetAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetAuthorResponse\x12)\n" +
	"\x06author\x18\x01 \x01(\v2\x11.author.v1.AuthorR\x06author\"\x14\n" +
	"\x12IndexAuthorRequest\"B\n" +
	"\x13IndexAuthorResponse\x12+\n" +
	"\aauthors\x18\x01 \x03(\v2\x11.author.v1.AuthorR\aauthors2\xfc\x01\n" +
	"\rAuthorService\x12Q\n" +
	"\fCreateAuthor\x12\x1e.author.v1.CreateAuthorRequest\x1a\x1f.author.v1.CreateAuthorResponse\"\x00\x12H\n" +
	"\tGetAuthor\x12\x1b.author.v1.GetAuthorRequest\x1a\x1c.author.v1.GetAuthorResponse\"\x00\x12N\n" +
	"\vIndexAuthor\x12\x1d.author.v1.IndexAuthorRequest\x1a\x1e.author.v1.IndexAuthorResponse\"\x00B0Z.github.com/AlyxPink/meower/api/proto/author/v1b\x06proto3"

var (
	file_author_v1_author_proto_rawDescOnce sync.Once
	file_author_v1_author_proto_rawDescData []byte
)

func file_author_v1_author_proto_rawDescGZIP() []byte {
	file_author_v1_author_proto_rawDescOnce.Do(func() {
		file_author_v1_author_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_author_v1_author_proto_rawDesc), len(file_author_v1_author_proto_rawDesc)))
	})
	return file_author_v1_author_proto_rawDescData
}

var file_author_v1_author_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_author_v1_author_proto_goTypes = []any{
	(*Author)(nil),               // 0: author.v1.Author
	(*CreateAuthorRequest)(nil),  // 1: author.v1.CreateAuthorRequest
	(*CreateAuthorResponse)(nil), // 2: author.v1.CreateAuthorResponse
	(*GetAuthorRequest)(nil),     // 3: author.v1.GetAuthorRequest
	(*GetAuthorResponse)(nil),    // 4: author.v1.GetAuthorResponse
	(*IndexAuthorRequest)(nil),   // 5: author.v1.IndexAuthorRequest
	(*IndexAuthorResponse)(nil),  // 6: author.v1.IndexAuthorResponse
}
var file_author_v1_author_proto_depIdxs = []int32{
	0, // 0: author.v1.CreateAuthorResponse.author:type_name -> author.v1.Author
	0, // 1: author.v1.GetAuthorResponse.author:type_name -> author.v1.Author
	0, // 2: author.v1.IndexAuthorResponse.authors:type_name -> author.v1.Author
	1, // 3: author.v1.AuthorService.CreateAuthor:input_type -> author.v1.CreateAuthorRequest
	3, // 4: author.v1.AuthorService.GetAuthor:input_type -> author.v1.GetAuthorRequest
	5, // 5: author.v1.AuthorService.IndexAuthor:input_type -> author.v1.IndexAuthorRequest
	2, // 6: author.v1.AuthorService.CreateAuthor:output_type -> author.v1.CreateAuthorResponse
	4, // 7: author.v1.AuthorService.GetAuthor:output_type -> author.v1.GetAuthorResponse
	6, // 8: author.v1.AuthorService.IndexAuthor:output_type -> author.v1.IndexAuthorResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_author_v1_author_proto_init() }
func file_author_v1_author_proto_init() {
	if File_author_v1_author_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_author_v1_author_proto_rawDesc), len(file_author_v1_author_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_author_v1_author_proto_goTypes,
		DependencyIndexes: file_author_v1_author_proto_depIdxs,
		MessageInfos:      file_author_v1_author_proto_msgTypes,
	}.Build()
	File_author_v1_author_proto = out.File
	file_author_v1_author_proto_goTypes = nil
	file_author_v1_author_proto_depIdxs = nil
}
